postgres 10.3
user default postgres: postgres
password: chupaPedro
port: 5432


CREATE TABLE DAYS (
	DAY_ID SERIAL PRIMARY KEY,
	DAY INTEGER NOT NULL,
	MONTH INTEGER NOT NULL,
	YEAR INTEGER NOT NULL,
	DAY_OF_WEEK INTEGER, 
	FULL_DATE DATE
)


CREATE TABLE WEEKS (
	WEEK_ID PRIMARY KEY NOT NULL,
	WEEK_NUM INTEGER NOT NULL,
	FK_DAY_ID INTEGER REFERENCES DAYS (DAY_ID)
)

CREATE TABLE TIMES (
	TIME_ID SERIAL PRIMARY KEY,
	HORA INTEGER,
	FK_DAY_ID INTEGER REFERECENCES
)

CREATE TABLE DRIVERS (
	DRIVER_ID CHAR(100) PRIMARY KEY,
	DRIVER_NAME CHAR(200),
	DRIVER_EMAIL CHAR(200),
	DRIVER_PHONE CHAR(50),
	GENDER BOOL,
	CPF CHAR(11),
	CREATED_AT INTEGER REFERENCES DAYS(DAY_ID)
)

CREATE TABLE JOURNEYS (
	JOURNEY_ID CHAR(100) PRIMARY KEY,
	CHAR(20) END_STATE,
	FK_DRIVER_ID CHAR(100) REFERENCES DRIVERS(DRIVER_ID),
	FK_TIME_ID INTEGER REFERENCES TIMES (TIME_ID)
)

CREATE TABLE DRIVERS_RESULTS (
	FK_DRIVER_ID CHAR(100) REFERENCES DRIVERS(DRIVER_ID),
	FK_TIME_ID INTEGER REFERENCES TIMES(TIME_ID),
	CONNECTION REAL,
	DO INTEGER,
	COST REAL
)
